# Generated by Django 5.1.3 on 2024-11-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_book_page_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='book',
            name='relevant_words',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(),
        ),
    ]
