# Generated by Django 5.1.3 on 2024-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_remove_book_is_favorite_remove_book_relevant_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
