# Generated by Django 5.1.3 on 2024-11-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0010_book_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_favorite',
        ),
    ]
