# Generated by Django 5.1.3 on 2024-11-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='books/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdf')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
