# Generated by Django 5.1.3 on 2024-11-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
